(test
 (name test_raoui)
 (libraries raoui alcotest))

(test
 (name test_backend)
 (libraries raoui alcotest str))

(test
 (name test_unicode_string)
 (libraries raoui alcotest))

(test
 (name test_r_lexer)
 (libraries raoui alcotest))

(test
 (name test_ark_integration)
 (libraries raoui alcotest eio_main))
