(test
 (name test_raoui)
 (libraries raoui alcotest))

(test
 (name test_unicode_string)
 (libraries raoui alcotest))

(test
 (name test_r_lexer)
 (libraries raoui alcotest))

(test
 (name test_r_highlight)
 (libraries raoui alcotest))

(test
 (name test_tty_listener)
 (libraries raoui alcotest))

(test
 (name test_history)
 (libraries raoui alcotest))

(test
 (name test_md_layout)
 (libraries raoui alcotest))
