(library
 (name raoui)
 (libraries
  unix
  terminal_size
  eio
  eio.unix
  eio_main
  cohttp-eio
  yojson
  logs
  ptime
  sqlite3
  uutf
  uuseg
  uucp
  sedlex
  cmarkit
  otoml)
 (foreign_stubs
  (language c)
  (names rffi_stubs)
  (include_dirs ../c_ffi)
  (flags
   (:standard -std=c99)))
 (foreign_archives ../c_ffi/r_ffi_c)
 (preprocess
  (per_module
   ((pps sedlex.ppx)
    r_lexer))))
